version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: npm install
      - run: CI=true npm run build
      - run: npm test
  build_angga:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Angga's build"
workflows:
  version: 2
  angga_work:
    jobs:
      - build
      - build_angga:
          requires:
            - build
